using TerraFX.Interop.Windows;

namespace WinApiConsole;

/// <param name="RepeatCount">Indicates that a key is being held down. For example, when a key is held down, you might get five events with this member equal to 1, one event with this member equal to 5, or multiple events with this member greater than or equal to 1.</param>
/// <param name="Char">The character the key represents.</param>
/// <param name="KeyCode">A virtual key code that identifies the given key in a device-independent manner.</param>
/// <param name="ScanCode">The virtual scan code of the given key that represents the device-dependent value generated by the keyboard hardware.</param>
/// <param name="ControlKeys">The state of the control keys.</param>
public sealed record KeyEvent(
	bool KeyDown,
	ushort RepeatCount,
	char Char, //TODO can it be null?
	ushort KeyCode, //TODO use some winforms/wpf enum?
	ushort ScanCode, //TODO any existing enum for this?
	ControlKeyStates ControlKeys) : InputRecord
{
	internal static KeyEvent FromNative(KEY_EVENT_RECORD r)
		=> new(r.bKeyDown, r.wRepeatCount, r.uChar.UnicodeChar, r.wVirtualKeyCode, r.wVirtualScanCode, (ControlKeyStates)r.dwControlKeyState);
}